### ISSUE TITLE
yarn install fails on nexus.wdf.sap.corp

### ISSUE THREAD

**Issue by leon-vg** [petermuessig/ui5-sample-apollo#6]
Hi Peter and Damian,

I tried to get this repo up and running by following the 'Getting Started' instruction. However, I soon ran into an error where yarn couldn't find nexus.wdf.sap.corp:

```
error An unexpected error occurred: "http://nexus.wdf.sap.corp:8081/nexus/repository/build.milestones.npm/memorystream/-/memorystream-0.3.1.tgz: getaddrinfo ENOTFOUND nexus.wdf.sap.corp"
```

Removing the yarn.lock and retrying fixed the issue. Perhaps you can remove the yarn.lock or remake this file with publicly available sources.

**Comment by leon-vg** [comment]
I created a pull request to fix this issue and also added a missing step in the 'Getting Started' instructions.
https://github.com/petermuessig/ui5-sample-apollo/pull/7

**Comment by petermuessig** [comment]
PR has been merged. Many thanks!

**Comment by leon-vg** [comment]
You're welcome! Nice solution by the way for using node-modules in UI5. Until now, I never figured a good way to achieve this!
